### ISSUE TITLE
[Bug] Can't Connect to PS3

### ISSUE THREAD

**Issue by harislaksliosda** [ohhsodead/arisen-studio#74]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

my console ps3 can't connect with arisen, the apps just freeze

### Expected Behavior

arisen studio and my console connected

### Steps To Reproduce

07:13:17 [INFO] <1>: Loading application settings data... 
07:13:17 [INFO] <1>: Settings data doesn't exist, a new one has been created. 
07:13:17 [INFO] <1>: Backup files data doesn't exist, a new one has been created. 
07:13:17 [INFO] <1>: Successfully loaded application settings data. 
07:13:17 [INFO] <1>: Checking for Internet connection... 
07:13:17 [INFO] <1>: Internet connection detected. 
07:13:18 [INFO] <1>: Checking application for new updates... 
07:13:19 [INFO] <1>: You're currently using the latest version of Arisen Studio (Beta v3.0.1) 
07:17:57 [INFO] <1>: Initializing the application database... 
07:20:13 [INFO] <1>: Successfully loaded the database - Finalizing application data... 
07:20:13 [INFO] <1>: Initialized Arisen Studio (Beta v3.0.1) - Ready to connect... 
07:26:26 [INFO] <1>: Connecting to: myConsole (192.168.0.116) 

### Screenshots

![image](https://user-images.githubusercontent.com/43292550/196068529-0ff94725-946f-47ac-8141-049f7acb8ed8.png)

**Comment by ohhsodead** [comment]
@harislaksliosda do you have discord?

**Comment by ohhsodead** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> my console ps3 can't connect with arisen, the apps just freeze
> 
> ### Expected Behavior
> arisen studio and my console connected
> 
> ### Steps To Reproduce
> 07:13:17 [INFO] <1>: Loading application settings data... 07:13:17 [INFO] <1>: Settings data doesn't exist, a new one has been created. 07:13:17 [INFO] <1>: Backup files data doesn't exist, a new one has been created. 07:13:17 [INFO] <1>: Successfully loaded application settings data. 07:13:17 [INFO] <1>: Checking for Internet connection... 07:13:17 [INFO] <1>: Internet connection detected. 07:13:18 [INFO] <1>: Checking application for new updates... 07:13:19 [INFO] <1>: You're currently using the latest version of Arisen Studio (Beta v3.0.1) 07:17:57 [INFO] <1>: Initializing the application database... 07:20:13 [INFO] <1>: Successfully loaded the database - Finalizing application data... 07:20:13 [INFO] <1>: Initialized Arisen Studio (Beta v3.0.1) - Ready to connect... 07:26:26 [INFO] <1>: Connecting to: myConsole (192.168.0.116)
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/43292550/196068529-0ff94725-946f-47ac-8141-049f7acb8ed8.png)
> 
> ### Anything else?
> _No response_

does it crash after with an error message? make sure to have rebug toolbox or mutliman open when connecting to console

**Comment by harislaksliosda** [comment]
> @harislaksliosda do you have discord?

harries92 at discord

**Comment by ohhsodead** [comment]
Fixed by opening in administrator mode
