### ISSUE TITLE
an error occured code 425 message error in data connection

### ISSUE THREAD

**Issue by wildfirebill** [ohhsodead/arisen-studio#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error code pops up when trying to connect to ps3

### Screenshots

![Capture](https://user-images.githubusercontent.com/8473557/227784966-e9f357c2-6bdc-4b2e-b3e5-1fd8bbae352c.JPG)

### Anything else?

also how do i fix this tried multiple resolutions but it is the same
![Captue](https://user-images.githubusercontent.com/8473557/227785135-30e885ab-1716-4298-8418-525ae7a8df20.JPG)

**Comment by ohhsodead** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Current Behavior
> 
> error code pops up when trying to connect to ps3
> 
> ### Expected Behavior
> 
> _No response_
> 
> ### Steps To Reproduce
> 
> _No response_
> 
> ### Screenshots
> 
> ![Capture](https://user-images.githubusercontent.com/8473557/227784966-e9f357c2-6bdc-4b2e-b3e5-1fd8bbae352c.JPG)
> 
> 
> ### Anything else?
> 
> also how do i fix this tried multiple resolutions but it is the same
> ![Captue](https://user-images.githubusercontent.com/8473557/227785135-30e885ab-1716-4298-8418-525ae7a8df20.JPG)
> 

Should be fixed in latest update?

As for that mess, is it for all popups?

**Comment by 6jarjar6** [comment]
Same issue for me

**Comment by ohhsodead** [comment]
> Same issue for me. [Beta v3.0.2](https://github.com/ohhsodead/arisen-studio/releases/tag/0.3.0.2) Works for me though. Trying to figure out how to disable auto update.

I will change the FTP settings back and release update.

Currently no feature to disable auto update.

**Comment by ohhsodead** [comment]
Thanks for reporting, should be fixed now in [Beta 3.0.4](https://github.com/ohhsodead/arisen-studio/releases/tag/0.3.0.4)
