### ISSUE TITLE
[Feature]: Quick Start

### ISSUE THREAD

**Issue by cbarney813** [ohhsodead/arisen-studio#76]
### Description

Simple quick start guides to get the user started.

### Suggested Solution

Same as above.

**Comment by ohhsodead** [comment]
I have started a simple little guide on the [site](https://arisen.studio/guide)

**Comment by ohhsodead** [comment]
Thanks for the suggestion. I have improved the quick start guide when launching application, and also now doesn't stop showing at every launch until you confirm you have read it.
