### ISSUE TITLE
APP DOESNT WORK AT ALL[Bug]

### ISSUE THREAD

**Issue by NewUser12345123** [ohhsodead/arisen-studio#77]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

APP DOESNT WORK OR DO ANYTHING
THERE ARE NO MODS
WHAT I THINK I SAW 15 GTA MODS.... COOL, NOT
WTF

ANYWAY THERE IS NOTHING TO DOWNLOAD

AND ON TOP OF THE THE GUI IS HORRENDOUS, ABSOLUTELY NO OFFENSE
YOU JUST HAVE ALL THESE BUTTONS THAT DONT DO ANYTHING. WTF

JUST MAKE IT A DROP DOWN LIST

AND MAKE THINGS WORK

IM BAFFLED THAT NO ONE ELSE IS SAYING THIS TO YOU

NOTHING IN YOUR APP WORKS ONCE THE APP OPENS

### Expected Behavior

I EXPECT TO BE ABLE TO SEARCH A DATABSE OF MODS WITHIN TEN SECONDS OF OPENING THE APP

I SPENT 10 MINUTES TRYING TO FIGURE IT OUT

THEN THE ONLY WAY PEOPLE CAN CONTACT YOU IS THROUGH DISCORD?????? OF ALL PLACES

GIVE ME A BREAK

GOOD LUCK BRO
SHEESH

### Steps To Reproduce

OPEN PROGRAM,
TRY TO USE IT,
REALIZE IT DOESNT WORK

**Comment by ohhsodead** [comment]
> ### Is there an existing issue for this?
> 
> - [x] I have searched the existing issues
> 
> ### Current Behavior
> 
> APP DOESNT WORK OR DO ANYTHING
> THERE ARE NO MODS
> WHAT I THINK I SAW 15 GTA MODS.... COOL, NOT
> WTF
> 
> ANYWAY THERE IS NOTHING TO DOWNLOAD
> 
> 
> AND ON TOP OF THE THE GUI IS HORRENDOUS, ABSOLUTELY NO OFFENSE
> YOU JUST HAVE ALL THESE BUTTONS THAT DONT DO ANYTHING. WTF
> 
> JUST MAKE IT A DROP DOWN LIST
> 
> AND MAKE THINGS WORK
> 
> IM BAFFLED THAT NO ONE ELSE IS SAYING THIS TO YOU
> 
> 
> NOTHING IN YOUR APP WORKS ONCE THE APP OPENS
> 
> ### Expected Behavior
> 
> I EXPECT TO BE ABLE TO SEARCH A DATABSE OF MODS WITHIN TEN SECONDS OF OPENING THE APP
> 
> I SPENT 10 MINUTES TRYING TO FIGURE IT OUT
> 
> THEN THE ONLY WAY PEOPLE CAN CONTACT YOU IS THROUGH DISCORD?????? OF ALL PLACES
> 
> GIVE ME A BREAK
> 
> 
> 
> GOOD LUCK BRO
> SHEESH
> 
> ### Steps To Reproduce
> 
> OPEN PROGRAM,
> TRY TO USE IT,
> REALIZE IT DOESNT WORK
> 
> ### Screenshots
> 
> _No response_
> 
> ### Anything else?
> 
> _No response_

It really isn't difficult to use. You should have reached out if it was any issues. Since the release of the project about 3 years ago there hasn't been any comments like this

**Comment by ohhsodead** [comment]
@NewUser12345123

It really isn't difficult to use. You should have reached out if it was any issues. Since the release of the project about 3 years ago there hasn't been any comments like this.

**Comment by ohhsodead** [comment]
Closing due to frivolousness
