### ISSUE TITLE
[Bug] The Elder Scrolls V: Skyrim BLUS30778 save "Start at Level 90 w/ 10000 Stats" wrong file format

### ISSUE THREAD

**Issue by goldug** [ohhsodead/arisen-studio#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's a zip-file with .pkg file extension. It should have a .zip file extension.

### Expected Behavior

I expect it to be a .zip-file that can be opened.

### Steps To Reproduce

Download it.

**Comment by ohhsodead** [comment]
Thanks for reporting! It's now fixed for next update.
