### ISSUE TITLE
[Bug]: App force close after launch

### ISSUE THREAD

**Issue by erpskwerps** [ohhsodead/arisen-studio#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App starts up but force close after few seconds.
Currently using windows 11, is there any compatibility issue with it?
Using latest version available.

Big thanks for help and checking

### Expected Behavior

App launces normally

**Comment by ohhsodead** [comment]
Issue has been fixed now, it was due to invalid characters when I updated the homebrew database. Thank you for reporting it! :)
